### PR TITLE
Merge branch-TimeFormatBugFix-Qiaoran with Master

### LINKED ISSUE #169: [PE-D][Tester B] No validation of event's time (24H format)
An invalid time format of 24:39 is allowed by the `editEvent` command.

After entering the command:

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ish1506/ped#3

### LINKED ISSUE #172: [PE-D][Tester B] Bug in time format validation (24H format)
Similar to issue #3, for the addEvent command:

A time of `t/00:65` is allowed.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ish1506/ped#4

### LINKED ISSUE #185: [PE-D][Tester C] editEvent time format does not work for hh/mm/AM or hh/mm/PM
editEvent time format does not work for hh/mm/AM or hh/mm/PM as stated in the user guide.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ongwenpin/ped#3

### PR DESCRIPTION
**Pull request by Qiaoran-M**
Closes #169
Closes #172
Closes #185
This branch is built on MailingList UserGuide PR in case the mailing list part get erased by this PR.

### CODE REVIEW

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 1]
```diff
@@ -3,55 +3,55 @@
...
-    private static final DateTimeFormatter checkFormatter = DateTimeFormatter
-            .ofPattern("[HH:MM][hh/mm/a][h/mm/a][hh/m/a][h/m/a]");
-
-    //for changing to storage friendly format
-    private static final DateTimeFormatter logFormatter = DateTimeFormatter.ofPattern("hh/mm/a");
-
-    //for changing to user-readable format
-    private static final DateTimeFormatter outputFormatter = DateTimeFormatter.ofPattern("hh:mm a");
-
+    public static final String MESSAGE_FORMAT_CONSTRAINTS = "Start time must be in format: hh:mm.";
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: I think omit the fullstop here so as to not confuse the reader

```suggestion
    public static final String MESSAGE_FORMAT_CONSTRAINTS = "Start time must be in format: hh:mm";
```

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 2]
```diff
@@ -3,55 +3,55 @@
...
+    public static final String MESSAGE_VALUE_CONSTRAINTS = "%s exceeds the range of valid time value.";
+    private static final DecimalFormat df = new DecimalFormat("00");
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: I think class-level constants should be in uppercase

```suggestion
    private static final DecimalFormat DF = new DecimalFormat("00");
```

Also, you can consider giving it a more descriptive name because `DF` doesn't mean much to the reader. Alternatively, you can include a comment to explain what this constant does.

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 3]
```diff
@@ -3,55 +3,55 @@
...
-     *
      * @param startTime A valid start time.
      */
     public StartTime(String startTime) {
         requireNonNull(startTime);
         assert !startTime.isBlank();
-        checkArgument(isValidStartTime(startTime), MESSAGE_CONSTRAINTS);
-        this.time = LocalTime.parse(startTime, checkFormatter);
+        checkArgument(isValidStartTime(startTime) != 0, MESSAGE_FORMAT_CONSTRAINTS);
+        checkArgument(isValidStartTime(startTime) != -1, String.format(MESSAGE_VALUE_CONSTRAINTS, startTime));
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: Now that `isValidStartTime()` returns an integer, and not a boolean, I think it's not good to use the `checkArgument()` method here. The `checkArgument()` method was designed for boolean check functions, so passing in a check function that returns an integer with an unsual condition to "make" it return a boolean, may cause confusion for the reader.

I think a better way to perform the validation check is to use `if-else` clauses, similar to how you did it in the `ParserUtil#parseStartTime()` method.

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 4]
```diff
@@ -3,55 +3,55 @@
...
+        String [] parsedTime = startTime.split(":", 2);
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: Extra space after `String`. Also, the colon should be placed as a class-level constant (e.g. `TIME_DELIMITER`) to give it more meaning and to reduce literal duplication since you use it at multiple places in this class.

```suggestion
        String[] parsedTime = startTime.split(TIME_DELIMITER, 2);
```

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 5]
```diff
@@ -3,55 +3,55 @@
...
+        this.time = LocalTime.of(Integer.parseInt(parsedTime[0]), Integer.parseInt(parsedTime[1]), 0);
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: Java actually provides a `LocalTime.of()` method that sets the "seconds" param to 0 by default! 😄

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/LocalTime.html#of(int,int)

```suggestion
        this.time = LocalTime.of(Integer.parseInt(parsedTime[0]), Integer.parseInt(parsedTime[1]));
```

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 6]
```diff
@@ -3,55 +3,55 @@
...
+     * @return int value, 0 represent invalid time format, -1 represents invalid time value, 1 represents valid time.
      */
-    //found from https://mkyong.com/java/how-to-check-if-date-is-valid-in-java/
-    public static boolean isValidStartTime(String test) {
+    public static int isValidStartTime(String test) {
         try {
-            LocalTime.parse(test, checkFormatter);
-        } catch (DateTimeParseException e) {
-            return false;
+            String [] parsedTime = test.split(":", 2);
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: Same comment as the above `.split()` line

```suggestion
            String[] parsedTime = test.split(TIME_DELIMITER, 2);
```

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 7]
```diff
@@ -3,55 +3,55 @@
...
 
     /**
-     * Returns true if a given string is a valid StartTime input.
-     * @return boolean
+     * Checks if a given string is a valid StartTime input.
+     * @return int value, 0 represent invalid time format, -1 represents invalid time value, 1 represents valid time.
      */
-    //found from https://mkyong.com/java/how-to-check-if-date-is-valid-in-java/
-    public static boolean isValidStartTime(String test) {
+    public static int isValidStartTime(String test) {
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: Hmm I'm not sure if it's a good idea to convert this method to return an integer instead of a boolean. I understand you're doing this to distinguish between whether the time format is invalid or whether the time value is invalid. But doing so makes this method inconsistent with the other `isValidXXX()` methods in other classes since they all return a boolean.

Having said that, I can't think of any good alternatives to solve this issue. 😅 So I'm fine if you don't change this.

The only thing I can suggest is to consider using regex to validate the input string instead of actually trying to create the `LocalTime` object with the given inputs. While this doesn't solve the original problem, it could help shorten the method and make it more readable. But I'm not sure if you're comfortable with the regex syntax, so it's fine if you don't do so.

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 8]
```diff
@@ -3,55 +3,55 @@
...
         try {
-            LocalTime.parse(test, checkFormatter);
-        } catch (DateTimeParseException e) {
-            return false;
+            String [] parsedTime = test.split(":", 2);
+            Integer formatCheck = Integer.parseInt(parsedTime[0]) + Integer.parseInt(parsedTime[1]);
+            boolean lengthCheck = parsedTime[0].length() == 2 && parsedTime[1].length() == 2;
+            LocalTime.of(Integer.parseInt(parsedTime[0]), Integer.parseInt(parsedTime[1]), 0);
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: Same as above `LocalTime.of()` line

```suggestion
            LocalTime.of(Integer.parseInt(parsedTime[0]), Integer.parseInt(parsedTime[1]));
```

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 9]
```diff
@@ -83,7 +83,7 @@ public boolean equals(Object other) {
 
     @Override
     public String toString() {
-        return this.time.format(outputFormatter);
+        return String.format("%s:%s", df.format(this.time.getHour()), df.format(this.time.getMinute()));
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: Looks like `toString()` returns the same output as `toLogFormat()`. Perhaps set `toString()` to call `toLogFormat()` instead to reduce code duplication?

```suggestion
        return toLogFormat();
```

**Review by Benjamin-Sim — CHANGES_REQUESTED** [review]
All good except for some small changes! 👍

Also, I think you should update the user guide and event command error messages with the new time format.

File: src/main/java/seedu/address/model/event/StartTime.java (hunk 7 above)
Comment (Qiaoran-M) [reply src/main/java/seedu/address/model/event/StartTime.java]: I also thought about the inconsistency issue when changing the return type of this method. Maybe I can try adding another method in StartTime class named `isValidStartTimeValue(String test)` to check if the value is valid, so that`isValidStartTime(String test)` only needs to check the time format and it can preserve the boolean return value.

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 10]
```diff
@@ -14,46 +14,50 @@
  */
 public class StartTime implements Comparable<StartTime> {
 
-    public static final String MESSAGE_FORMAT_CONSTRAINTS = "Start time must be in format: hh:mm.";
+    public static final String MESSAGE_FORMAT_CONSTRAINTS = "Start time must be in format: hh:mm,"
+            + " hh and mm must be zero padded number of length 2, eg. 02:30";
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]:
```suggestion
            + " hh and mm must be a zero padded number of length 2, e.g. 02:30";
```

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 11]
```diff
@@ -14,46 +14,50 @@
...
     }
 
     /**
-     * Checks if a given string is a valid StartTime input.
-     * @return int value, 0 represent invalid time format, -1 represents invalid time value, 1 represents valid time.
+     * Checks if a given string follows the valid StartTime input format.
+     * @return boolean value.
      */
-    public static int isValidStartTime(String test) {
+    public static boolean isValidStartTime(String test) {
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: Perhaps it's good to rename this method to `isValidStartTimeFormat()` to better differentiate it from `isValidStartTimeValue()`?

```suggestion
    public static boolean isValidStartTimeFormat(String test) {
```

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 12]
```diff
@@ -14,46 +14,50 @@
...
+        return test.matches(VALIDATION_REGEX);
+    }
+
+    /**
+     * Checks if a given string can be parsed to a valid StartTime value.
+     * @param test string input, it is guaranteed that the format check for test is done before this function.
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: I don't think it's a good idea to guarantee that the format check is done before this function, because a method can't guarantee who calls it or when it's called.

```suggestion
     * @param test string input, the format check for test should be done before calling this function.
```

File: src/main/java/seedu/address/model/event/StartTime.java (hunk 4 above)
Comment (Benjamin-Sim) [reply src/main/java/seedu/address/model/event/StartTime.java]: ^^

File: src/main/java/seedu/address/model/event/StartTime.java (hunk 6 above)
Comment (Benjamin-Sim) [reply src/main/java/seedu/address/model/event/StartTime.java]: ^^

**Review by Benjamin-Sim — CHANGES_REQUESTED** [review]
Splitting `isValidStartTime()` into 2 methods makes it much easier to understand. 👍

Although this kinda breaks the abstraction since the caller must know that there are 2 `isValidXX()` methods needed to validate a `StartTime` object, instead of 1 `isValidXX()` method for other objects. But I think this is a good tradeoff to make in this case.

Just a few more edits and this can be merged!

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 13]
```diff
@@ -28,28 +30,28 @@ public class StartTime implements Comparable<StartTime> {
     public StartTime(String startTime) {
         requireNonNull(startTime);
         assert !startTime.isBlank();
-        checkArgument(isValidStartTime(startTime), MESSAGE_FORMAT_CONSTRAINTS);
+        checkArgument(isValidStartTimeFormat(startTime), MESSAGE_FORMAT_CONSTRAINTS);
         checkArgument(isValidStartTimeValue(startTime), String.format(MESSAGE_VALUE_CONSTRAINTS, startTime));
-        String [] parsedTime = startTime.split(":", 2);
+        String [] parsedTime = startTime.split(TIME_DELIMITER, 2);
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: Extra space after `String`

```suggestion
        String[] parsedTime = startTime.split(TIME_DELIMITER, 2);
```

File: src/main/java/seedu/address/model/event/StartTime.java [hunk 14]
```diff
@@ -28,28 +30,28 @@ public class StartTime implements Comparable<StartTime> {
...
     /**
      * Checks if a given string can be parsed to a valid StartTime value.
-     * @param test string input, it is guaranteed that the format check for test is done before this function.
+     * @param test string input, the format check for test should be done before calling this function.
      * @return boolean value.
      */
     public static boolean isValidStartTimeValue(String test) {
         try {
-            String [] parsedTime = test.split(":", 2);
+            String [] parsedTime = test.split(TIME_DELIMITER, 2);
```
Comment (Benjamin-Sim) [inline src/main/java/seedu/address/model/event/StartTime.java]: Extra space after `String`

```suggestion
            String[] parsedTime = test.split(TIME_DELIMITER, 2);
```

**Review by Benjamin-Sim — CHANGES_REQUESTED** [review]
Just 2 more minor edits!

File: src/main/java/seedu/address/model/event/StartTime.java (hunk 14 above)
Comment (Qiaoran-M) [reply src/main/java/seedu/address/model/event/StartTime.java]: Thanks for spotting this! i forgot to change this line

**Review by Benjamin-Sim — APPROVED** [review]
LGTM! 👍
