### PR TITLE
Merge branch-FixBugs-V1.3 with Master

### LINKED ISSUE #143: makeStats Command Error Message
The `makeStats` command error message is missing a space between words

Capture

### LINKED ISSUE #144: AppUtil#checkArgument() has extra System.out.println
The `AppUtil#checkArgument()` method has an extra line `System.out.println("Hello")`. Looks like someone used it to detect when that method was being executed and forgot to remove it.

Capture2

### LINKED ISSUE #146: PieChart labels are aligned wrongly
When the user calls a `makeStats` command once, the labels appear fine.

However, upon closing the window and calling the same command again, the labels will be aligned to the same position.

image

### LINKED ISSUE #147: PieChart slices are labelled wrongly
Currently, the calculation for ageGroup slices are wrong in the `makeStats` command.

There should not be a slice for age group 10 - 15 year olds in the image shown below.
image

### PR DESCRIPTION
**Pull request by lfrostbytee**
Closes #147 
Closes #146 
Closes #144 
Closes #143

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -65,8 +65,9 @@ public Uid getUid() {
 
     public String getAgeGroup() {
         int age = dob.toAge();
-        age = (int) (Math.ceil(age / AGE_GROUP_SIZE) * AGE_GROUP_SIZE);
-        return String.format("%d-%dyo", age - AGE_GROUP_SIZE, age);
+        age = (int) (Math.floor(age / AGE_GROUP_SIZE) * AGE_GROUP_SIZE);
```
Comment (tanhl2000) [inline src/main/java/seedu/address/model/person/Person.java]: minAgeInGroup would be a better variable name

File: src/main/java/seedu/address/ui/StatsWindow.java [hunk 2]
```diff
@@ -42,8 +44,17 @@ public StatsWindow() {
     /**
      * Replaces the current data used to generate the {@code PieChart} with the new data specified.
      */
+    //Solution adapted from: https://stackoverflow.com/questions/36276805/how-to-wrap-text-of-a-javafx-chart-legend
     public void setPieChart(ObservableList<PieChart.Data> newData) {
         chart.setData(newData);
+        for (Node node : chart.lookupAll(".chart-legend-item")) {
+            if (node instanceof Label) {
+                Label n = (Label) node;
```
Comment (tanhl2000) [inline src/main/java/seedu/address/ui/StatsWindow.java]: rename n to legendElement or something similar? maybe put a comment as to what this does as well which is to wrap the text in the legend

**Review by tanhl2000 — CHANGES_REQUESTED** [review]

**Review by tanhl2000 — APPROVED** [review]
LGTM thx for the changes!
