### PR TITLE
Merge Branch-editEventComand-Vinod with master

### LINKED ISSUE #91: Add exceptions for Event class
Event class currently borrows some exceptions from Persons or uses the Exception class directly. It needs to have it own implementation of Exceptions in order for the program to have more information on the specific exception that occurred.

### LINKED ISSUE #92: Create editEvent feature for Event class
As a marketer with many marketing events, I should be able to edit a marketing event that I have previously input, so that I can keep my addressbook up to date with the latest changes in events.

### PR DESCRIPTION
**Pull request by Vinodjayakumar124**
Closes #92; Closes #91

### CODE REVIEW

File: src/main/java/seedu/address/model/AddressBook.java [hunk 1]
```diff
@@ -130,6 +130,20 @@ public void deleteEvent(Event e) {
...
+    public boolean hasEvent(Event event) {
+        requireNonNull(event);
+        return events.contains(event);
+    }
+
+    public void setEvent(Event target, Event editedEvent) {
+        requireNonNull(editedEvent);
+
+        events.setEvent(target, editedEvent);
+    }
```
Comment (lfrostbytee) [inline src/main/java/seedu/address/model/AddressBook.java]: Perhaps you might want to add JavaDocs for the `setEvent` method similar to `setPerson`'s JavaDocs

File: src/main/java/seedu/address/model/Model.java [hunk 2]
```diff
@@ -93,6 +93,10 @@ public interface Model {
      */
     void deleteEvent(Event event);
 
+    void setEvent(Event target, Event editedEvent);
+
+    boolean hasEvent(Event target);
```
Comment (lfrostbytee) [inline src/main/java/seedu/address/model/Model.java]: Perhaps you might want to add JavaDoc for these 2 methods?

File: src/main/java/seedu/address/logic/commands/EditEventCommand.java [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+    public static final String MESSAGE_DUPLICATE_EVENT = "This event already exists in the address book.";
+
+    private final Index index;
+
+    private final EditEventDescriptor editEventDescriptor;
+
+    /**
+     * Constructor of the EditEventCommand class
+     * @param index of the event to be edited in the filtered event list
+     * @param editEventDescriptor details to edit the event with
```
Comment (lfrostbytee) [inline src/main/java/seedu/address/logic/commands/EditEventCommand.java]: May require full stops.
```suggestion
     * Constructor of the EditEventCommand class.
     * @param index of the event to be edited in the filtered event list.
     * @param editEventDescriptor details to edit the event with.
```

File: src/main/java/seedu/address/logic/commands/EditEventCommand.java [hunk 4]
```diff
@@ -0,0 +1,195 @@
...
+        }
+
+        model.setEvent(eventToEdit, editedEvent);
+        model.updateFilteredEventList(Model.PREDICATE_SHOW_ALL_EVENTS);
+        return new CommandResult(String.format(MESSAGE_EDIT_EVENT_SUCCESS, editedEvent));
+    }
+
+    /**
+     * Creates and returns a {@code Event} with the details of {@code eventToEdit} that is edited
+     * with details of {@code editEventDescriptor}
```
Comment (lfrostbytee) [inline src/main/java/seedu/address/logic/commands/EditEventCommand.java]: May require full stop.
```suggestion
     * with details of {@code editEventDescriptor}.
```

File: src/main/java/seedu/address/logic/commands/EditEventCommand.java [hunk 5]
```diff
@@ -0,0 +1,195 @@
...
+    public static class EditEventDescriptor {
+        private String eventTitle;
+        private StartDate date;
+        private StartTime time;
+        private String purpose;
+
+        public EditEventDescriptor() {}
+
+        /**
+         * Constructor to create a {@code EditEventDescriptor} object
```
Comment (lfrostbytee) [inline src/main/java/seedu/address/logic/commands/EditEventCommand.java]: May require full stop.
```suggestion
         * Constructor to create a {@code EditEventDescriptor} object.
```

**Review by lfrostbytee — COMMENTED** [review]
Nice job! I have opened up an which requires `editEvent` to be updated once `Event` and its attributes have been properly implemented:
- #112 editEvent shouldn't be allowed to make eventTitle empty
Other than that, there are some minor errors.

**Review by lfrostbytee — APPROVED** [review]
Other than the merge conflicts, lgtm!

**Review by lfrostbytee — APPROVED** [review]
Lgtm!
